/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	_ "log"
	"net/http"
	_ "net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	db "github.com/nguyenduchoan9/coderschool.go/assignment.2/goapi/src/db"
	sw "github.com/nguyenduchoan9/coderschool.go/assignment.2/goapi/src/go"
)

func main() {
	// log.Printf("Server started")

	// router := sw.NewRouter()

	// log.Fatal(http.ListenAndServe(":8080", router))
	db.ConnectDB()
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
	defer db.DisconnectDB()
}
